"""Offline mock provider.

The mock reads the *same prompt* a real model would receive (figure label,
embedded text, requested JSON keys) and produces a deterministic, well-formed
answer. It is used in-process (provider type ``mock``) and by the mock HTTP
server (``spec2kb mock-server``), which speaks the OpenAI-compatible protocol so
that the real HTTP adapter can be tested end to end without network access.

Options (provider ``extra_body`` or request body):
  mock_hallucinate: true   -> adds an invented timing value (tests the validator)
  mock_fail: "always"      -> every call fails (tests error handling)
  mock_latency_ms: 300     -> artificial latency
"""

from __future__ import annotations

import hashlib
import json
import re
import time
from typing import Any

from .base import Provider, ProviderError, ProviderResponse

KEY_LINE_RE = re.compile(r'^- "(\w+)":', re.M)
NAME_KEYS = {"signals", "pins", "components", "states", "elements", "series", "columns", "views", "layout", "axes"}
VALUE_KEYS = {"parameters", "key_points", "dimensions"}
FLOW_KEYS = {"sequence", "transitions", "connections", "rows"}
NUM_RE = re.compile(r"\d")

MOCK_OCR_TEXT = (
    "MOCK OCR TRANSCRIPTION\n\n"
    "This text was produced by the offline mock provider. It does not read the page image. "
    "Configure a real vision or OCR provider to transcribe scanned pages."
)


def _embedded(prompt: str) -> list[str]:
    m = re.search(r"Text found inside the figure region[^\n]*:\n(.*?)(?:\n\s*\n|\Z)", prompt, re.S)
    if not m:
        return []
    out = []
    for ln in m.group(1).splitlines():
        ln = ln.strip().lstrip("-• ").strip()
        if ln and ln != "(none)":
            out.append(ln)
    return out


def _label(prompt: str) -> str:
    m = re.search(r"^Figure:\s*(.+)$", prompt, re.M)
    return m.group(1).strip() if m else "Figure"


def mock_generate(system: str, prompt: str, has_image: bool, options: dict[str, Any] | None = None) -> str:
    options = options or {}
    if options.get("mock_fail") == "always":
        raise ProviderError("mock provider configured to fail (mock_fail=always)", retryable=False, status=500)
    if options.get("mock_latency_ms"):
        time.sleep(min(10.0, float(options["mock_latency_ms"]) / 1000))
    low = prompt.lower()
    if "transcribe" in low and "scanned" in low:
        return MOCK_OCR_TEXT
    if "classify" in low and "reply with the id only" in low:
        ids = re.findall(r"^- (\w+):", prompt, re.M)
        cap = re.search(r"Caption:\s*(.*)", prompt)
        cap_text = (cap.group(1) if cap else "").lower()
        for kw, tid in (("timing", "timing_diagram"), ("state", "state_diagram"), ("block", "block_diagram"),
                        ("ball", "pinout"), ("pin", "pinout"), ("graph", "chart")):
            if kw in cap_text and tid in ids:
                return tid
        return "generic" if "generic" in ids else (ids[0] if ids else "generic")
    if "reply with the word ok" in low:
        return "OK"
    keys = [k for k in KEY_LINE_RE.findall(prompt) if k not in ("summary", "uncertain")]
    labels = _embedded(prompt)
    label = _label(prompt)
    names = [l for l in labels if not NUM_RE.search(l)][:12]
    values = [l for l in labels if NUM_RE.search(l)][:12]
    result: dict[str, Any] = {
        "summary": f"{label}. Offline mock description built from {len(labels)} text label(s) found in the figure region."
                   + ("" if has_image else " (no image was attached)"),
    }
    for k in keys:
        if k in NAME_KEYS:
            result[k] = names or ["(no text labels found in the figure region)"]
        elif k in VALUE_KEYS:
            result[k] = list(values)
            if options.get("mock_hallucinate"):
                result[k].append("tFAKE = 9.99 ns")
        elif k in FLOW_KEYS:
            result[k] = [f"{a} -> {b}" for a, b in zip(names, names[1:])][:6]
        elif k == "notes":
            result[k] = ["Generated by the offline mock provider; replace with a real vision model for production."]
        else:
            result[k] = labels[:8]
    result["uncertain"] = [] if labels else ["The figure has no text layer; nothing could be cross-checked (mock)."]
    return json.dumps(result, ensure_ascii=False, indent=2)


class MockProvider(Provider):
    def complete(self, *, system: str, prompt: str, images: list[bytes] | None = None,
                 max_tokens: int = 1500, temperature: float = 0.0) -> ProviderResponse:
        t0 = time.monotonic()
        text = mock_generate(system, prompt, bool(images), self.config.extra_body)
        digest = hashlib.sha1(prompt.encode()).hexdigest()[:8]
        return ProviderResponse(text=text, model=self.config.model or "mock-vision-1",
                                latency_ms=int((time.monotonic() - t0) * 1000),
                                usage={"prompt_hash": digest})
